define(function () {
    const questions = [
        {
            "id": "7a612c4c-3495-4a41-8ed5-535d98227595",
            "options": ["möchten", "wünschen", "hoffen", "träumen"],
            "sentence": "Wir _____ uns, dass unsere Kinder gesund und glücklich sind.",
            "translation": "We wish that our children are healthy and happy.",
            "translationUkr": "Ми бажаємо, щоб наші діти були здорові та щасливі.",
            "answer": "wünschen",
        },
        {
            "id": "fcfcd34d-e192-4cbb-b4ab-9b02715c53cc",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____ davon, die Welt zu bereisen.",
            "translation": "I dream of traveling the world.",
            "translationUkr": "Я мрію подорожувати світом.",
            "answer": "träume",
        },
        {
            "id": "4b5f37ee-9ae6-4b2d-800a-cab71cbfba7a",
            "options": ["möchtest", "wünschst", "hoffst", "träumst"],
            "sentence": "Du _____ dir einen neuen Job.",
            "translation": "You wish for a new job.",
            "translationUkr": "Ти бажаєш собі нову роботу.",
            "answer": "wünschst",
        },
        {
            "id": "b7743157-5895-4103-b387-4e1b8d7b6372",
            "options": ["möchte", "wünscht", "hofft", "träumt"],
            "sentence": "Sie _____, ihre Eltern bald zu besuchen.",
            "translation": "She hopes to visit her parents soon.",
            "translationUkr": "Вона сподівається незабаром відвідати своїх батьків.",
            "answer": "hofft",
        },
        {
            "id": "66182115-a6d5-4d9a-a867-86eab1b055ee",
            "options": ["möchten", "wünschen", "hoffen", "träumen"],
            "sentence": "Viele Menschen _____ von einem besseren Leben.",
            "translation": "Many people dream of a better life.",
            "translationUkr": "Багато людей мріють про краще життя.",
            "answer": "träumen",
        },
        {
            "id": "29db7dec-ef7d-4323-baff-162cfe5ec565",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____, dass ich im Lotto gewinne.",
            "translation": "I hope that I win the lottery.",
            "translationUkr": "Я сподіваюся, що виграю в лотерею.",
            "answer": "hoffe",
        },
        {
            "id": "a42cf18e-57f3-498c-a6fa-e966ec5190d3",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____ mir eine Gehaltserhöhung.",
            "translation": "I wish for a salary increase.",
            "translationUkr": "Я бажаю собі підвищення зарплати.",
            "answer": "wünsche",
        },
        {
            "id": "c2d5be40-0268-4da6-a596-908e93af3a49",
            "options": ["möchtest", "wünschst", "hoffst", "träumst"],
            "sentence": "Du _____ davon, ein erfolgreicher Schriftsteller zu werden.",
            "translation": "You dream of becoming a successful writer.",
            "translationUkr": "Ти мрієш стати успішним письменником.",
            "answer": "träumst",
        },
        {
            "id": "dbd159e6-10d7-4f2c-af05-d4cdf93714a6",
            "options": ["möchte", "wünscht", "hofft", "träumt"],
            "sentence": "Er _____ sich ein neues Auto.",
            "translation": "He wishes for a new car.",
            "translationUkr": "Він бажає собі нову машину.",
            "answer": "wünscht",
        },
        {
            "id": "edbda380-d0ea-4e46-8f44-fbd14b850c4a",
            "options": ["möchten", "wünschen", "hoffen", "träumen"],
            "sentence": "Wir _____, dass unsere Kinder eine gute Ausbildung bekommen.",
            "translation": "We hope that our children get a good education.",
            "translationUkr": "Ми сподіваємося, що наші діти отримають хорошу освіту.",
            "answer": "hoffen",
        },
        {
            "id": "68c65265-3652-4183-907e-b2cbc1f50c7a",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____ davon, einmal um die Welt zu segeln.",
            "translation": "I dream of sailing around the world one day.",
            "translationUkr": "Я мрію одного дня обпливти навколо світу.",
            "answer": "träume",
        },
        {
            "id": "7ec49261-9684-49c5-a7db-29ac61b8dd67",
            "options": ["möchtest", "wünschst", "hoffst", "träumst"],
            "sentence": "Du _____ dir mehr Freizeit.",
            "translation": "You wish for more free time.",
            "translationUkr": "Ти бажаєш собі більше вільного часу.",
            "answer": "wünschst",
        },
        {
            "id": "6af17741-01b0-4c91-a282-a61f9b16f02d",
            "options": ["möchte", "wünscht", "hofft", "träumt"],
            "sentence": "Sie _____, bald eine Familie zu gründen.",
            "translation": "She hopes to start a family soon.",
            "translationUkr": "Вона сподівається незабаром створити сім'ю.",
            "answer": "hofft",
        },
        {
            "id": "92e9f87c-feb8-4b8d-9df3-1ba27cd82304",
            "options": ["möchten", "wünschen", "hoffen", "träumen"],
            "sentence": "Viele Kinder _____ davon, Fußballprofi zu werden.",
            "translation": "Many children dream of becoming a professional football player.",
            "translationUkr": "Багато дітей мріють стати професійними футболістами.",
            "answer": "träumen",
        },
        {
            "id": "c0e7dc86-c4ad-4d91-b121-81543c3acbdc",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____, dass ich bald eine eigene Wohnung finde.",
            "translation": "I hope that I find my own apartment soon.",
            "translationUkr": "Я сподіваюся, що незабаром знайду власну квартиру.",
            "answer": "hoffe",
        },
        {
            "id": "49597623-032c-49ba-bf73-563b1bd3ecc8",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____ mir, dass meine Kinder glücklich und erfolgreich sind.",
            "translation": "I wish that my children are happy and successful.",
            "translationUkr": "Я бажаю, щоб мої діти були щасливі та успішні.",
            "answer": "wünsche",
        },
        {
            "id": "4a508483-68b3-44ca-8799-6762656551ce",
            "options": ["möchtest", "wünschst", "hoffst", "träumst"],
            "sentence": "Du _____ davon, ein eigenes Geschäft zu eröffnen.",
            "translation": "You dream of opening your own business.",
            "translationUkr": "Ти мрієш відкрити власний бізнес.",
            "answer": "träumst",
        },
        {
            "id": "3d1b5cde-66e3-4a67-9984-8120afe12923",
            "options": ["möchte", "wünscht", "hofft", "träumt"],
            "sentence": "Er _____ sich mehr Anerkennung für seine Arbeit.",
            "translation": "He wishes for more recognition for his work.",
            "translationUkr": "Він бажає більше визнання за свою роботу.",
            "answer": "wünscht",
        },
        {
            "id": "3e3336c5-d32d-4223-a676-b4ceacd17d37",
            "options": ["möchten", "wünschen", "hoffen", "träumen"],
            "sentence": "Wir _____, dass wir bald in den Urlaub fahren können.",
            "translation": "We hope that we can go on vacation soon.",
            "translationUkr": "Ми сподіваємося, що зможемо незабаром поїхати у відпустку.",
            "answer": "hoffen",
        },
        {
            "id": "bc84aee6-a837-4dce-a2e1-a96a6b8a57e9",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____ davon, ein Buch zu schreiben.",
            "translation": "I dream of writing a book.",
            "translationUkr": "Я мрію написати книгу.",
            "answer": "träume",
        },
        {
            "id": "fb52e2b6-d9ce-4eca-ac2f-97aee3f4a0f9",
            "options": ["möchtest", "wünschst", "hoffst", "träumst"],
            "sentence": "Du _____ dir einen Hund als Haustier.",
            "translation": "You wish for a dog as a pet.",
            "translationUkr": "Ти бажаєш собі собаку в якості домашнього улюбленця.",
            "answer": "wünschst",
        },
        {
            "id": "f60d190d-723b-4d93-a04b-3d42c3f3e94d",
            "options": ["möchte", "wünscht", "hofft", "träumt"],
            "sentence": "Sie _____, dass ihr Sohn ein guter Mensch wird.",
            "translation": "She hopes that her son becomes a good person.",
            "translationUkr": "Вона сподівається, що її син стане хорошою людиною.",
            "answer": "hofft",
        },
        {
            "id": "60b6db8f-bdf9-4fbc-ab7a-820202f17143",
            "options": ["möchten", "wünschen", "hoffen", "träumen"],
            "sentence": "Viele Menschen _____ von einem Leben ohne Stress.",
            "translation": "Many people dream of a life without stress.",
            "translationUkr": "Багато людей мріють про життя без стресу.",
            "answer": "träumen",
        },
        {
            "id": "9143e6a5-5d93-4c3a-b342-3b4ad5c03ab3",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____, dass ich bald eine Beförderung bekomme.",
            "translation": "I hope that I get a promotion soon.",
            "translationUkr": "Я сподіваюся, що незабаром отримаю підвищення.",
            "answer": "hoffe",
        },
        {
            "id": "fd1d01b7-799f-46d6-a6e3-470862a5e084",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____ mir, dass meine Familie immer gesund bleibt.",
            "translation": "I wish that my family always stays healthy.",
            "translationUkr": "Я бажаю, щоб моя родина завжди була здоровою.",
            "answer": "wünsche",
        },
        {
            "id": "546df879-21d9-4a11-9785-8408cb6d3475",
            "options": ["möchtest", "wünschst", "hoffst", "träumst"],
            "sentence": "Du _____ davon, einmal nach New York zu reisen.",
            "translation": "You dream of traveling to New York one day.",
            "translationUkr": "Ти мрієш одного дня поїхати в Нью-Йорк.",
            "answer": "träumst",
        },
        {
            "id": "ff87aa75-b8e5-40f3-aafb-3f91b406fb7d",
            "options": ["möchte", "wünscht", "hofft", "träumt"],
            "sentence": "Er _____ sich mehr Zeit für seine Hobbys.",
            "translation": "He wishes for more time for his hobbies.",
            "translationUkr": "Він бажає більше часу для своїх хобі.",
            "answer": "wünscht",
        },
        {
            "id": "8d9f11aa-1edf-417e-abe8-17bfb10c34f7",
            "options": ["möchten", "wünschen", "hoffen", "träumen"],
            "sentence": "Wir _____, dass wir bald eine größere Wohnung finden.",
            "translation": "We hope that we find a bigger apartment soon.",
            "translationUkr": "Ми сподіваємося, що незабаром знайдемо більшу квартиру.",
            "answer": "hoffen",
        },
        {
            "id": "150bd113-74d4-4e0a-8b98-e43594e385ae",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____ davon, einmal in einem Schloss zu übernachten.",
            "translation": "I dream of staying in a castle one day.",
            "translationUkr": "Я мрію одного дня переночувати в замку.",
            "answer": "träume",
        },
        {
            "id": "ea602e4a-5a1e-4b22-91cd-0f1e3fe940bd",
            "options": ["möchtest", "wünschst", "hoffst", "träumst"],
            "sentence": "Du _____ dir ein neues Handy zum Geburtstag.",
            "translation": "You wish for a new cell phone for your birthday.",
            "translationUkr": "Ти бажаєш собі новий мобільний телефон на день народження.",
            "answer": "wünschst",
        },
        {
            "id": "7e45bcfb-bf24-4c8d-ab57-d773977d14e7",
            "options": ["möchte", "wünscht", "hofft", "träumt"],
            "sentence": "Sie _____, dass sie bald den richtigen Partner findet.",
            "translation": "She hopes that she finds the right partner soon.",
            "translationUkr": "Вона сподівається, що незабаром знайде правильного партнера.",
            "answer": "hofft",
        },
        {
            "id": "2abd8066-c17d-4567-a82f-e510ca8d646e",
            "options": ["möchten", "wünschen", "hoffen", "träumen"],
            "sentence": "Viele Menschen _____ von einem Leben im Ausland.",
            "translation": "Many people dream of a life abroad.",
            "translationUkr": "Багато людей мріють про життя за кордоном.",
            "answer": "träumen",
        },
        {
            "id": "1cb27ab4-3818-4375-ab58-68c06bd7cae6",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____, dass ich bald meinen Traumjob finde.",
            "translation": "I hope that I find my dream job soon.",
            "translationUkr": "Я сподіваюся, що незабаром знайду роботу своєї мрії.",
            "answer": "hoffe",
        },
        {
            "id": "02e48554-63b1-4834-952c-0bbd1ccef748",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____ mir, dass ich mehr Zeit mit meinen Freunden verbringen kann.",
            "translation": "I wish that I can spend more time with my friends.",
            "translationUkr": "Я бажаю, щоб я міг проводити більше часу зі своїми друзями.",
            "answer": "wünsche",
        },
        {
            "id": "313af63f-a2bc-4dd9-9070-6a92239c403a",
            "options": ["möchtest", "wünschst", "hoffst", "träumst"],
            "sentence": "Du _____ davon, einmal eine Weltreise zu machen.",
            "translation": "You dream of going on a world trip one day.",
            "translationUkr": "Ти мрієш одного дня здійснити навколосвітню подорож.",
            "answer": "träumst",
        },
        {
            "id": "a11411fd-2785-4cd6-aa78-838b3dde13f1",
            "options": ["möchte", "wünscht", "hofft", "träumt"],
            "sentence": "Er _____ sich ein neues Fahrrad zum Geburtstag.",
            "translation": "He wishes for a new bicycle for his birthday.",
            "translationUkr": "Він бажає собі новий велосипед на день народження.",
            "answer": "wünscht",
        },
        {
            "id": "ad7a28b8-ee3b-4c5c-b6fd-a9b118520748",
            "options": ["möchten", "wünschen", "hoffen", "träumen"],
            "sentence": "Wir _____, dass wir bald mehr Zeit für unsere Hobbys haben.",
            "translation": "We hope that we have more time for our hobbies soon.",
            "translationUkr": "Ми сподіваємося, що незабаром матимемо більше часу для наших хобі.",
            "answer": "hoffen",
        },
        {
            "id": "9bf84403-ee9f-44e1-a9d2-1143d0a53c92",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____ davon, einmal auf einem Bauernhof zu leben.",
            "translation": "I dream of living on a farm one day.",
            "translationUkr": "Я мрію одного дня жити на фермі.",
            "answer": "träume",
        },
        {
            "id": "4efe3942-b89f-4403-9556-f849b3f107ee",
            "options": ["möchtest", "wünschst", "hoffst", "träumst"],
            "sentence": "Du _____ dir mehr Freizeit und weniger Stress.",
            "translation": "You wish for more free time and less stress.",
            "translationUkr": "Ти бажаєш більше вільного часу і менше стресу.",
            "answer": "wünschst",
        },
        {
            "id": "74eabd72-7eca-40eb-9776-18f9f3bdafe8",
            "options": ["möchte", "wünscht", "hofft", "träumt"],
            "sentence": "Sie _____, dass sie bald ihr Studium abschließt.",
            "translation": "She hopes that she finishes her studies soon.",
            "translationUkr": "Вона сподівається, що незабаром закінчить навчання.",
            "answer": "hofft",
        },
        {
            "id": "4a2c21d6-a875-485d-a1fc-f978a20ccaad",
            "options": ["möchten", "wünschen", "hoffen", "träumen"],
            "sentence": "Viele Menschen _____ von einem Leben ohne finanzielle Sorgen.",
            "translation": "Many people dream of a life without financial worries.",
            "translationUkr": "Багато людей мріють про життя без фінансових турбот.",
            "answer": "träumen",
        },
        {
            "id": "51853e9e-e4d2-40c7-96a3-423c27a8c8aa",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____, dass ich bald eine eigene Familie gründen kann.",
            "translation": "I hope that I can start my own family soon.",
            "translationUkr": "Я сподіваюся, що незабаром зможу створити власну сім'ю.",
            "answer": "hoffe",
        },
        {
            "id": "478552e1-0f68-4cca-b7e7-afcf3771a3a6",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____ mir, dass ich mehr Geduld und Verständnis für andere habe.",
            "translation": "I wish that I have more patience and understanding for others.",
            "translationUkr": "Я бажаю, щоб у мене було більше терпіння і розуміння до інших.",
            "answer": "wünsche",
        },
        {
            "id": "e13c6dd1-ebc6-41de-8d38-cf0543468e5d",
            "options": ["möchtest", "wünschst", "hoffst", "träumst"],
            "sentence": "Du _____ davon, einmal ein eigenes Haus zu bauen.",
            "translation": "You dream of building your own house one day.",
            "translationUkr": "Ти мрієш одного дня побудувати власний будинок.",
            "answer": "träumst",
        },
        {
            "id": "91c4338f-7515-4021-9e6f-7aca4fad7e25",
            "options": ["möchte", "wünscht", "hofft", "träumt"],
            "sentence": "Er _____ sich mehr Anerkennung und Respekt von anderen.",
            "translation": "He wishes for more recognition and respect from others.",
            "translationUkr": "Він бажає більше визнання і поваги від інших.",
            "answer": "wünscht",
        },
        {
            "id": "99fbbe40-ccba-4770-8cc3-75e061d02f20",
            "options": ["möchten", "wünschen", "hoffen", "träumen"],
            "sentence": "Wir _____, dass wir bald einen schönen Urlaub machen können.",
            "translation": "We hope that we can go on a nice vacation soon.",
            "translationUkr": "Ми сподіваємося, що незабаром зможемо поїхати у гарну відпустку.",
            "answer": "hoffen",
        },
        {
            "id": "38380f16-8f18-4daf-83a0-ba0c547d9cad",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____ davon, einmal ein eigenes Restaurant zu eröffnen.",
            "translation": "I dream of opening my own restaurant one day.",
            "translationUkr": "Я мрію одного дня відкрити власний ресторан.",
            "answer": "träume",
        },
        {
            "id": "2da72200-0e26-4267-8995-9d2c75c6d552",
            "options": ["möchtest", "wünschst", "hoffst", "träumst"],
            "sentence": "Du _____ dir, dass du mehr Zeit für deine Familie hast.",
            "translation": "You wish that you have more time for your family.",
            "translationUkr": "Ти бажаєш, щоб у тебе було більше часу для своєї сім'ї.",
            "answer": "wünschst",
        },
        {
            "id": "9b53e490-cd7d-41e8-b3f8-a96261907272",
            "options": ["möchte", "wünscht", "hofft", "träumt"],
            "sentence": "Sie _____, dass sie bald eine Gehaltserhöhung bekommt.",
            "translation": "She hopes that she gets a salary increase soon.",
            "translationUkr": "Вона сподівається, що незабаром отримає підвищення зарплати.",
            "answer": "hofft",
        },
        {
            "id": "f4a327b2-78c5-4b7b-a7ea-8aaf02d6bb99",
            "options": ["möchten", "wünschen", "hoffen", "träumen"],
            "sentence": "Viele Kinder _____ davon, einmal Astronaut zu werden.",
            "translation": "Many children dream of becoming an astronaut one day.",
            "translationUkr": "Багато дітей мріють одного дня стати астронавтами.",
            "answer": "träumen",
        },
        {
            "id": "462861eb-4348-48cb-b4c5-accc5a7b4fc5",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____, dass ich bald meinen Führerschein mache.",
            "translation": "I hope that I get my driver's license soon.",
            "translationUkr": "Я сподіваюся, що незабаром отримаю водійські права.",
            "answer": "hoffe",
        },
        {
            "id": "a91abf9d-4154-4d44-94c6-654a3d697a32",
            "options": ["möchte", "wünsche", "hoffe", "träume"],
            "sentence": "Ich _____ mir, dass ich mehr Zeit für mich selbst habe.",
            "translation": "I wish that I have more time for myself.",
            "translationUkr": "Я бажаю, щоб у мене було більше часу для себе.",
            "answer": "wünsche",
        }
    ]

    return questions;
});