define(function () {
    const questions = [
        {
            "id": "18647adb-6204-42fd-a4ed-8fb042576762",
            "options": ["ich", "mich", "mir", "ihn"],
            "sentence": "Sie arbeitet mit _____ (ich + D).",
            "translation": "She works with me",
            "translationUkr": "Вона працює зі мною.",
            "answer": "mir",
        },
        {
            "id": "8d36c436-3f97-4152-ab1c-ab1b9c0a03e6",
            "options": ["du", "mir", "dich", "dir"],
            "sentence": "Ich kaufe _____ (du + D) ein Geschenk.",
            "translation": "I am buying you a gift.",
            "translationUkr": "Я купую тобі подарунок.",
            "answer": "dir",
        },
        {
            "id": "261a75e5-6a90-430c-95e1-9d8fadd1d2af",
            "options": ["sich", "ihm", "ihn", "sie"],
            "sentence": "Er sieht _____ (er + A) im Spiegel.",
            "translation": "He sees himself in the mirror.",
            "translationUkr": "Він бачить себе в дзеркалі.",
            "answer": "sich",
        },
        {
            "id": "c1cdb722-7fbe-4ff0-9fdd-e062efbea559",
            "options": ["sich", "ihr", "sie", "es"],
            "sentence": "Sie macht _____ (sie + D) einen Kaffee.",
            "translation": "She is making herself a coffee.",
            "translationUkr": "Вона робить собі каву.",
            "answer": "sich",
        },
        {
            "id": "3a73beae-a720-405b-9c54-7081ba503c30",
            "options": ["sie", "ihnen", "ihre", "ihn"],
            "sentence": "Ich gebe _____ (sie (plural) + D) die Bücher.",
            "translation": "I give them the books.",
            "translationUkr": "Я даю їм книги.",
            "answer": "ihnen",
        },
        {
            "id": "8ee0a804-e49d-4b5d-9c19-d57ee741d3d4",
            "options": ["ihn", "ihm", "er", "seine"],
            "sentence": "Wir helfen _____ (er + D) immer.",
            "translation": "We always help him.",
            "translationUkr": "Ми завжди допомагаємо йому.",
            "answer": "ihm",
        },
        {
            "id": "8c805689-56f3-49c7-9cfc-3f50defb3152",
            "options": ["sie", "ihr", "ihre", "ihn"],
            "sentence": "Ich kenne _____ (sie (singular) + A) gut.",
            "translation": "I know her well.",
            "translationUkr": "Я добре знаю її.",
            "answer": "sie",
        },
        {
            "id": "a459c7e6-c987-49d6-bf6a-b444afbbc319",
            "options": ["sie", "ihr", "ihre", "ihn"],
            "sentence": "Ich helfe _____ (sie (singular) + D) gerne.",
            "translation": "I gladly help her.",
            "translationUkr": "Я із задоволенням допомагаю їй.",
            "answer": "ihr",
        },
        {
            "id": "c12aee5b-e7ec-4457-9381-63b54082e9f0",
            "options": ["uns", "wir", "unser", "sich"],
            "sentence": "Wir treffen _____ (wir + A) im Park.",
            "translation": "We meet each other in the park.",
            "translationUkr": "Ми зустрічаємося в парку.",
            "answer": "uns",
        },
        {
            "id": "73c949b4-7894-4e40-89b5-fc0369874fda",
            "options": ["euch", "ihr", "eure", "sich"],
            "sentence": "Ich sehe _____ (ihr + A) morgen.",
            "translation": "I see you tomorrow.",
            "translationUkr": "Я побачу вас завтра.",
            "answer": "euch",
        },
        {
            "id": "637a4cc4-b914-45be-8efb-bf46370f5589",
            "options": ["mich", "mir", "ich", "sich"],
            "sentence": "Ich kaufe _____ (ich + D) ein neues Auto.",
            "translation": "I am buying myself a new car.",
            "translationUkr": "Я купую собі нову машину.",
            "answer": "mir",
        },
        {
            "id": "00ea27fb-9d3a-4a8c-a8ac-0749c6f1ecac",
            "options": ["dich", "dir", "du", "sich"],
            "sentence": "Du solltest _____ (du + A) schonen.",
            "translation": "You should take care of yourself.",
            "translationUkr": "Ти повинен берегти себе.",
            "answer": "dich",
        },
        {
            "id": "95a29475-e862-4cac-a7af-3722474e745b",
            "options": ["uns", "wir", "unser", "sich"],
            "sentence": "Wir machen _____ (wir + D) Sorgen.",
            "translation": "We are worried about ourselves.",
            "translationUkr": "Ми турбуємося про себе.",
            "answer": "uns",
        },
        {
            "id": "c790c023-17bf-4358-8dc8-4b4be1e4d00d",
            "options": ["euch", "ihr", "eure", "sich"],
            "sentence": "Ihr könnt _____ (ihr + D) vertrauen.",
            "translation": "You can trust yourselves.",
            "translationUkr": "Ви можете довіряти собі.",
            "answer": "euch",
        },
        {
            "id": "4b8c1419-cf1d-42f0-a3a7-d125d60079f7",
            "options": ["ihm", "ihn", "er", "sich"],
            "sentence": "Er vertraut _____ (er + D) nicht.",
            "translation": "He doesn't trust himself.",
            "translationUkr": "Він не довіряє собі.",
            "answer": "sich",
        },
        {
            "id": "5f9f8238-cc44-4d04-aea6-55c7899d2583",
            "options": ["ihr", "sie", "ihre", "sich"],
            "sentence": "Sie liebt _____ (sie (singular) + A) sehr.",
            "translation": "He loves her very much.",
            "translationUkr": "Він дуже її любить.",
            "answer": "sie",
        },
        {
            "id": "4cf0fed6-be67-4759-b425-d664751c4e94",
            "options": ["es", "ihm", "sein", "sich"],
            "sentence": "Das Baby kann _____ (es + A) noch nicht selbst anziehen.",
            "translation": "The baby can't dress itself yet.",
            "translationUkr": "Дитина ще не може одягатися самостійно.",
            "answer": "sich",
        },
        {
            "id": "441c285d-f9ce-458a-bff1-02a5404004d1",
            "options": ["ihnen", "sie", "ihre", "sich"],
            "sentence": "Die Kinder waschen _____ (sie (plural) + A) die Hände.",
            "translation": "The children wash their hands.",
            "translationUkr": "Діти миють руки.",
            "answer": "sich",
        },
        {
            "id": "d9d33ef7-75f8-4259-a77e-4a879ecfc8a0",
            "options": ["uns", "wir", "unser", "sich"],
            "sentence": "Wir erinnern _____ (wir + A) an die schönen Zeiten.",
            "translation": "We remember the good times.",
            "translationUkr": "Ми згадуємо хороші часи.",
            "answer": "uns",
        },
        {
            "id": "0e747476-2ef6-4b69-9c9b-b80fb0b3993a",
            "options": ["euch", "ihr", "eure", "sich"],
            "sentence": "Ich wünsche _____ (ihr + D) viel Erfolg.",
            "translation": "I wish you much success.",
            "translationUkr": "Я бажаю вам великих успіхів.",
            "answer": "euch",
        },
        {
            "id": "bc830378-3739-4bf5-bec1-e8d038188c8c",
            "options": ["mich", "mir", "ich", "sich"],
            "sentence": "Ich freue _____ (ich + A) auf den Urlaub.",
            "translation": "I am looking forward to the vacation.",
            "translationUkr": "Я з нетерпінням чекаю на відпустку.",
            "answer": "mich",
        },
        {
            "id": "058d0b88-de96-4680-9cdf-78d58d7b7ff4",
            "options": ["dich", "dir", "du", "sich"],
            "sentence": "Ich glaube _____ (du + D).",
            "translation": "I believe you.",
            "translationUkr": "Я вірю тобі.",
            "answer": "dir",
        },
        {
            "id": "bf3c8a61-b859-490d-a1d3-9012099762d7",
            "options": ["uns", "wir", "unser", "sich"],
            "sentence": "Er gibt _____ (wir + D) die Schlüssel.",
            "translation": "He gives us the keys.",
            "translationUkr": "Він дає нам ключі.",
            "answer": "uns",
        },
        {
            "id": "88d3ff59-0078-41bf-8802-63a04e6dfe61",
            "options": ["euch", "ihr", "eure", "sich"],
            "sentence": "Ich besuche _____ (ihr + A) nächste Woche.",
            "translation": "I will visit you next week.",
            "translationUkr": "Я відвідаю вас наступного тижня.",
            "answer": "euch",
        },
        {
            "id": "c46f2f0d-b683-4759-a3ce-ccfa1a53a7be",
            "options": ["ihm", "ihn", "er", "sich"],
            "sentence": "Sie liebt _____ (er + A).",
            "translation": "She loves him.",
            "translationUkr": "Вона любить його.",
            "answer": "ihn",
        },
        {
            "id": "446e7f61-d600-45f4-96eb-9e6216ed57b7",
            "options": ["ihr", "sie", "ihre", "sich"],
            "sentence": "Er schenkt _____ (sie (singular) + D) Blumen.",
            "translation": "He gives her flowers.",
            "translationUkr": "Він дарує їй квіти.",
            "answer": "ihr",
        },
        {
            "id": "f93355ab-b581-4510-bf85-6dd687ec54e8",
            "options": ["es", "ihm", "sein", "sich"],
            "sentence": "Ich füttere _____ (es + A) jeden Morgen.",
            "translation": "I feed it every morning.",
            "translationUkr": "Я годую його щоранку.",
            "answer": "es",
        },
        {
            "id": "d55e5443-9e30-4916-9965-993c55fcef01",
            "options": ["ihnen", "sie", "ihre", "sich"],
            "sentence": "Er bringt _____ (sie (plural) + D) Geschenke mit.",
            "translation": "He brings them gifts.",
            "translationUkr": "Він приносить їм подарунки.",
            "answer": "ihnen",
        },
        {
            "id": "cac86e84-fb31-4dd9-af34-748e01711e8b",
            "options": ["uns", "wir", "unser", "sich"],
            "sentence": "Wir sollten _____ (wir + D) mehr Zeit nehmen.",
            "translation": "We should take more time for ourselves.",
            "translationUkr": "Ми повинні приділяти собі більше часу.",
            "answer": "uns",
        },
        {
            "id": "0ed3de25-c905-4856-9bce-382f774eeb5d",
            "options": ["euch", "ihr", "eure", "sich"],
            "sentence": "Ihr müsst _____ (ihr + A) beeilen.",
            "translation": "You have to hurry.",
            "translationUkr": "Ви повинні поспішати.",
            "answer": "euch",
        },
        {
            "id": "eb7002ba-82e1-4732-ac08-4ea419f80db0",
            "options": ["mich", "mir", "ich", "sich"],
            "sentence": "Ich sehe _____ (ich + A) im Spiegel.",
            "translation": "I see myself in the mirror.",
            "translationUkr": "Я бачу себе в дзеркалі.",
            "answer": "mich",
        },
        {
            "id": "7e34926b-aa89-4839-b2f6-50fb3fceb756",
            "options": ["dich", "dir", "du", "sich"],
            "sentence": "Du solltest _____ (du + D) mehr Zeit nehmen.",
            "translation": "You should take more time for yourself.",
            "translationUkr": "Ти повинен приділяти собі більше часу.",
            "answer": "dir",
        },
        {
            "id": "9b85a67f-1b63-4f80-9313-25524dd9909e",
            "options": ["uns", "wir", "unser", "sich"],
            "sentence": "Wir treffen _____ (wir + A) später.",
            "translation": "We'll meet later.",
            "translationUkr": "Ми зустрінемося пізніше.",
            "answer": "uns",
        },
        {
            "id": "e60b0613-4219-4ec7-bf30-998ed6c2f0a7",
            "options": ["euch", "ihr", "eure", "sich"],
            "sentence": "Ich rufe _____ (ihr + A) morgen an.",
            "translation": "I'll call you tomorrow.",
            "translationUkr": "Я зателефоную вам завтра.",
            "answer": "euch",
        },
        {
            "id": "32f841c9-7832-4d00-a8a5-b9e55faba900",
            "options": ["ihm", "ihn", "er", "sich"],
            "sentence": "Sie gibt _____ (er + D) das Buch.",
            "translation": "She gives him the book.",
            "translationUkr": "Вона дає йому книгу.",
            "answer": "ihm",
        },
        {
            "id": "1742a980-dea4-4b4d-9116-14c1284d3edc",
            "options": ["ihr", "sie", "ihre", "sich"],
            "sentence": "Er bringt _____ (sie (singular) + D) Kaffee.",
            "translation": "He brings her coffee.",
            "translationUkr": "Він приносить їй каву.",
            "answer": "ihr",
        },
        {
            "id": "0d8ef226-6efb-47ad-9d9e-00fe3ef2e74a",
            "options": ["es", "ihm", "sein", "sich"],
            "sentence": "Ich wasche _____ (es + A) jeden Tag.",
            "translation": "I wash it every day.",
            "translationUkr": "Я мию його щодня.",
            "answer": "es",
        },
        {
            "id": "a112129f-10e4-4fec-8e15-c506d7d4bc3a",
            "options": ["ihnen", "sie", "ihre", "sich"],
            "sentence": "Er erklärt _____ (sie (plural) + D) die Regeln.",
            "translation": "He explains the rules to them.",
            "translationUkr": "Він пояснює їм правила.",
            "answer": "ihnen",
        },
        {
            "id": "fffbedf7-0729-4af3-9b5d-e0753fc2a0df",
            "options": ["uns", "wir", "unser", "sich"],
            "sentence": "Wir freuen _____ (wir + A) auf den Urlaub.",
            "translation": "We are looking forward to the vacation.",
            "translationUkr": "Ми з нетерпінням чекаємо на відпустку.",
            "answer": "uns",
        },
        {
            "id": "ccc7ba6f-1f84-45e3-8bb2-110cb95a47be",
            "options": ["euch", "ihr", "eure", "sich"],
            "sentence": "Ich wünsche _____ (ihr + D) alles Gute.",
            "translation": "I wish you all the best.",
            "translationUkr": "Я бажаю вам всього найкращого.",
            "answer": "euch",
        },
        {
            "id": "ea41b3d6-d03e-41f9-aee7-7187063abc9b",
            "options": ["mich", "mir", "ich", "sich"],
            "sentence": "Ich wasche _____ (ich + D) die Hände.",
            "translation": "I wash my hands.",
            "translationUkr": "Я мию руки.",
            "answer": "mir",
        },
        {
            "id": "2fdea9e1-a430-4e4b-8708-a7a004a7cd36",
            "options": ["dich", "dir", "du", "sich"],
            "sentence": "Du solltest _____ (du + A) ausruhen.",
            "translation": "You should rest.",
            "translationUkr": "Ти повинен відпочити.",
            "answer": "dich",
        },
        {
            "id": "a68b1996-66a0-463b-8dde-4cab580211d6",
            "options": ["uns", "wir", "unser", "sich"],
            "sentence": "Wir holen _____ (wir + D) etwas zu trinken.",
            "translation": "We'll get ourselves something to drink.",
            "translationUkr": "Ми візьмемо собі щось випити.",
            "answer": "uns",
        },
        {
            "id": "3f54c716-0ade-4fbb-be09-8be1dff43534",
            "options": ["euch", "ihr", "eure", "sich"],
            "sentence": "Ihr solltet _____ (ihr + D) mehr Zeit nehmen.",
            "translation": "You should take more time for yourselves.",
            "translationUkr": "Ви повинні приділяти собі більше часу.",
            "answer": "euch",
        },
        {
            "id": "e35eeea4-3a46-4e15-ab8d-491ab9c767ec",
            "options": ["ihm", "ihn", "er", "sich"],
            "sentence": "Sie fragt _____ (er + A) nach seiner Meinung.",
            "translation": "She asks him for his opinion.",
            "translationUkr": "Вона запитує його про його думку.",
            "answer": "ihn",
        },
        {
            "id": "3dbb607f-1313-4387-9458-4bfc4ea2063f",
            "options": ["ihr", "sie", "ihre", "sich"],
            "sentence": "Er hilft _____ (sie (singular) + D) bei der Arbeit.",
            "translation": "He helps her with work.",
            "translationUkr": "Він допомагає їй з роботою.",
            "answer": "ihr",
        },
        {
            "id": "12bdf47f-b419-436d-b35f-1347cb0bd4e7",
            "options": ["es", "ihm", "sein", "sich"],
            "sentence": "Ich finde _____ (es + A) sehr interessant.",
            "translation": "I find it very interesting.",
            "translationUkr": "Я вважаю це дуже цікавим.",
            "answer": "es",
        },
        {
            "id": "31f2f058-1ac1-44f7-8cd5-e6386f0d20f2",
            "options": ["ihnen", "sie", "ihre", "sich"],
            "sentence": "Er zeigt _____ (sie (plural) + D) den Weg.",
            "translation": "He shows them the way.",
            "translationUkr": "Він показує їм дорогу.",
            "answer": "ihnen",
        },
        {
            "id": "0a1a6196-d7f1-4cc2-9eba-e93fb46cec05",
            "options": ["uns", "wir", "unser", "sich"],
            "sentence": "Wir sehen _____ (wir + A) morgen.",
            "translation": "We'll see each other tomorrow.",
            "translationUkr": "Ми побачимося завтра.",
            "answer": "uns",
        },
        {
            "id": "19abb2f1-61c9-4bb5-8278-d27e0fec1dab",
            "options": ["euch", "ihr", "eure", "sich"],
            "sentence": "Ich danke _____ (ihr + D) für die Hilfe.",
            "translation": "I thank you for your help.",
            "translationUkr": "Я дякую вам за допомогу.",
            "answer": "euch",
        }
    ]

    return questions;
});